/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "vsrc/top.v:1" *)
module top(select, a, b, c, d, out);
  (* src = "vsrc/top.v:2" *)
  input [1:0] a;
  (* src = "vsrc/top.v:2" *)
  input [1:0] b;
  (* src = "vsrc/top.v:2" *)
  input [1:0] c;
  (* src = "vsrc/top.v:2" *)
  input [1:0] d;
  (* src = "vsrc/top.v:3" *)
  output [1:0] out;
  (* src = "vsrc/top.v:2" *)
  input [1:0] select;
  (* module_not_derived = 32'd1 *)
  (* src = "vsrc/top.v:5" *)
  MuxKeyWithDefault #(
    .\$1 (32'sd4),
    .\$2 (32'sd2),
    .\$3 (32'sd2)
  ) i1 (
    out,
    select,
    2'h0,
    { 2'h0, a, 2'h1, b, 2'h2, c, 2'h3, d }
  );
endmodule
